config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 sign_up: 'register' }

  resources :admin, only: %i[index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :likes, only: %i[create]
  resources :posts, only: %i[index]

  resources :products, except: %i[destroy] do
    resources :posts, except: %i[index] do
      resources :comments, only: %i[create]
      get 'liked', on: :collection
    end
  end

  resources :cart, only: %i[index] do
    collection do
      get :content, format: :json
      post :add_product
      post :remove_product
      post :checkout
    end
  end

  resources :orders, only: %i[index]

  root to: 'products#index'
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  include ::Market::Cart::SessionMixin

  before_action :set_product, only: %i[add_product remove_product]
  before_action :set_cart, only: %i[index add_product remove_product checkout content]
  before_action :verify_cart_signature, only: %i[checkout]

  def index
    if @cart.empty?
      flash[:success] = 'Your cart is empty. Choose some product first.'
      redirect_to root_path
    end
  end

  def add_product
    @added_product = [@product.name, @cart.add(@product.id.to_s)]
  end

  def remove_product
    @remaining_product = [@product.name, @cart.remove(@product.id.to_s)]
  end

  def checkout
    current_user.orders.create.from_cart(@cart)
    @cart.clear
    flash[:success] = 'Your order was registered and will be processed soon.'
    redirect_to root_path
  end

  def content
    pricing = ::Market::Pricer.price(@cart)
    @content = pricing[:detail]
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def verify_cart_signature
    return if params[:cart_sign] == @cart.signature

    flash[:danger] = 'Cart content was updated in the meanwhile. Please reconfirm with current content.'
    redirect_to cart_index_path
  end
end

app/controllers/concerns/market/cart.rb
# frozen_string_literal: true

module Market
  module Cart
    module SessionMixin
      extend ActiveSupport::Concern

      included do
        def set_cart
          @cart = ::Market::Cart::Cart.new(session)
        end
      end
    end

    class Cart
      include Enumerable

      def initialize(session)
        @session = session
        @session[:cart] ||= {}
      end

      def clear
        @session[:cart] = {}
        @session.delete :cart_updated
      end

      def signature
        Digest::MD5.hexdigest(@session[:cart_updated].to_s)
      end

      def empty?
        @session[:cart].empty?
      end

      def present?(item_id)
        @session[:cart].key? item_id
      end

      def quantity(item_id)
        @session[:cart][item_id] || 0
      end

      def add(item_id)
        mark_update
        self[item_id] = quantity(item_id) + 1
      end

      def remove(item_id)
        mark_update
        qty = quantity(item_id) - 1
        if qty.positive?
          self[item_id] = qty
        else
          @session[:cart].delete(item_id)
          0
        end
      end

      def each(&block)
        cart = @session[:cart]
        if block_given?
          cart.each(&block)
        else
          cart.to_enum(__method__)
        end
      end

      def <<(item_id)
        add(item_id)
        self
      end

      def [](item_id)
        quantity(item_id)
      end

      private

      def []=(item_id, value)
        @session[:cart][item_id] = value
      end

      def mark_update
        @session[:cart_updated] = DateTime.now
      end
    end
  end
end

app/helpers/cart_helper.rb
# frozen_string_literal: true

module CartHelper
end

app/views/cart/add_product.js.haml
- product_name, qty = @added_product
alert("Your cart contains now #{qty} x product [#{product_name}].");

app/views/cart/index.html.haml
- content_for :packs, 'bootstrap-tempusdominus,bootstrap-table,market-cart-content'
- content_for :no_css_packs, 'market-cart-content'

.h3.text-center Cart content

%table.text-center#cart{ data: { url: content_cart_index_path, toggle: 'table' } }
  %thead
    %tr
      %th{ 'data-field': 'name' } Product
      %th{ 'data-field': 'qty' } Quantity
      %th{ 'data-field': 'price', 'data-formatter': 'cart_price_formatter' } Unit Price

%br/

.h3.text-center Delivery choices

= form_with url: checkout_cart_index_path do |f|
  = f.hidden_field :cart_sign, value: @cart.signature

  .form-row
    .col
      .input-group
        = f.label :delivery_hour_range, class: 'form-control col-sm-2'
        - hour_ranges = %w[8-12 12-14 14-16 16-18 18-20 20-21]
        = f.select :delivery_hour_range, hour_ranges, {}, { class: 'form-control col-sm-10' }

  .form-row
    .col
      .input-group.date#delivery_date_picker{ data: { 'target-input': 'nearest',
                                                      'date-format': 'YYYY-MM-DD' } }
        = f.label :delivery_date, class: 'form-control col-sm-2'
        = f.text_field :delivery_date, class: 'form-control datetimepicker-input', 'data-target': '#delivery_date_picker'
        .input-group-append{ data: { target: '#delivery_date_picker', toggle: 'datetimepicker' } }
          .input-group-text
            %i.fas.fa-calendar

  %br/

  .text-center
    = f.button 'Validate order', class: 'btn btn-primary'

app/views/cart/remove_product.js.haml
- product_name, qty = @remaining_product
- if qty.zero?
  alert("Product [#{product_name}] was removed from your cart.");
- else
  alert("Your cart contains now #{qty} x product [#{product_name}].");