config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 sign_up: 'register' }

  resources :admin, only: %i[index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :likes, only: %i[create]
  resources :posts, only: %i[index]

  resources :products, except: %i[destroy] do
    resources :posts, except: %i[index] do
      resources :comments, only: %i[create]
      get 'liked', on: :collection
    end
  end

  resources :cart, only: %i[index] do
    collection do
      get :content, format: :json
      post :add_product
      post :remove_product
      post :checkout
    end
  end

  resources :orders, only: %i[index]

  root to: 'products#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :content, length: { maximum: 2048 }
  belongs_to :user
  belongs_to :product

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  #mount_uploader :featured_image, FeaturedImageUploader

  def self.with_username
    joins(:user).select('posts.*, users.username as user_name')
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  respond_to :html

  before_action :set_product, only: %i[show new create]
  before_action :set_current_user_post, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def show
    flash.keep
    @post = Post.with_username.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = current_user.posts.new
  end

  def create
    post = current_user.posts.new(post_params)
    post.product_id = @product.id
    flash[:success] = 'Post was successfully created.' if post.save
    respond_with post.product, post
  end

  def edit
  end

  def update
    flash[:success] = 'Post was successfully updated.' if @post.update(post_params)
    respond_with @post.product, @post
  end

  def destroy
    flash[:success] = 'Post was successfully destroyed.' if @post.destroy
    respond_with @post.product, @post
  end

  #def followed
  #  @posts = current_user.followed_posts
  #  render :index
  #end

  def liked
    @posts = current_user.liked_posts
    render :index
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_current_user_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :featured_image, :featured_image_cache)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  HEADLINE_SIZE = 40

  def headline(post)
    post.content.truncate(HEADLINE_SIZE)
  end
end

app/views/posts/_form.html.haml
= form_with model: [:product, post] do |f|
  - if post.errors.any?
    #error_explanation
      %h2
        #{pluralize(post.errors.count, 'error')} prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :content, class: 'col-form-label'
    = f.text_area :content, rows: 15, id: 'post-content-area', class: 'form-control'

    %br/
    = f.button 'Submit', class: 'btn btn-primary'

app/views/posts/_post.html.haml
.card
  .card-header
    .row
      .col-sm-8
        At #{post.updated_at.to_s(:timestamp)}
        %i.fa.fa-user
        #{post.user_name} reviewed #{post.product.name}:
      .col-sm-4
        - if post.likes.size.positive?
          %div{data: { toggle: 'tooltip', html: true },
               title: post.liking_users.pluck(:username).join('<br/>')}
            = post.likes.size
            %i.far.fa-heart
        - else
          No
          %i.far.fa-thumbs-up
          yet !
          %i.fas.fa-heart-broken
  .card-body
    .card-text
      - if preview_mode
        .row
          .col-sm-10= headline(post)
      - else
        .row
          .col-sm-12= post.content
    .card-link
      %br/
      .row
        - if preview_mode
          .col
            = link_to product_post_path(post.product, post) do
              %i.fa.fa-eye
              View full post
        - if current_user.id == post.user_id
          .col
            = link_to edit_product_post_path(post.product, post) do
              %i.fa.fa-edit
              Edit post
          .col
            = link_to product_post_path(post.product, post), method: :delete, data: { confirm: 'Are you sure?' } do
              %i.far.fa-trash-alt
              Delete post
        - else
          .col
            - unless liked_posts_ids.include? post.id
              = link_to likes_path(id: post.id), method: :post do
                %i.far.fa-thumbs-up
                +1
%br/

app/views/posts/edit.html.haml
%h1 Editing post

= render partial: 'form', locals: { post: @post }

= link_to 'Show', @post

app/views/posts/index.html.haml
= render partial: 'post',
         collection: @posts.with_username.order(updated_at: :desc),
         as: 'post',
         locals: { liked_posts_ids: current_user.liked_posts.pluck(:id),
                   preview_mode: true }

app/views/posts/new.html.haml
%h1 Reviewing @post.product.name

= render partial: 'form', locals: { post: @post }

app/views/posts/show.html.haml
= render partial: 'post',
         locals: { post: @post,
                   liked_posts_ids: current_user.liked_posts.pluck(:id),
                   preview_mode: false }

%hr/

.h3 Comments
- @post.comments.with_username.order(:updated_at).each do |comment|
  .card
    .card-header
      At
      = comment.created_at.to_s(:timestamp)
      ,
      = comment.user_name
      said:
    .card-body
      .card-text
        = comment.content

%hr/

.h3 Say something too !
= render 'comments/form'