config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 sign_up: 'register' }

  resources :admin, only: %i[index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :likes, only: %i[create]
  resources :posts, only: %i[index]

  resources :products, except: %i[destroy] do
    resources :posts, except: %i[index] do
      resources :comments, only: %i[create]
      get 'liked', on: :collection
    end
  end

  resources :cart, only: %i[index] do
    collection do
      get :content, format: :json
      post :add_product
      post :remove_product
      post :checkout
    end
  end

  resources :orders, only: %i[index]

  root to: 'products#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 1, maximum: 60 }
  validates :description, presence: true, length: { minimum: 0, maximum: 1024 }

  has_many :snapshots, class_name: 'ProductSnapshot', inverse_of: :product
  has_many :posts

  scope :enabled, -> { where(enabled: true) }

  mount_uploader :photo, ProductImageUploader

  def snapshot
    snapshots.find_or_create_by(name: name, price: price)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  respond_to :html

  before_action :set_product, only: %i[show edit update]

  def index
    @cart = cart_from_session
  end

  def show
  end

  def new
    authorize :product
    @product = Product.new
  end

  def create
    authorize :product
    @product = Product.new(product_params)
    flash[:success] = 'Product was successfully created.' if @product.save
    respond_with @product
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    flash[:success] = 'Product was successfully updated.' if @product.update(product_params)
    respond_with @product
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo, :photo_cache, :order)
  end

  # TODO: extract to tools
  def cart_from_session
    session[:cart] ||= {}
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.haml
- content_for :packs, 'cloudinary-upload'
- content_for :no_css_packs, 'cloudinary-upload'

= form_with model: product do |f|
  - if product.errors.any?
    #error_explanation
      %h2 #{pluralize(product.errors.count, 'error')} prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.hidden_field :photo_cache
    .custom-file
      = f.label :photo, class: 'custom-file-label'
      = f.file_field :photo, class: 'custom-file-input'
    = f.label :name, class: 'col-form-label'
    = f.text_field :name, class: 'form-control'
    = f.label :price, class: 'col-form-label'
    = f.text_field :price, class: 'form-control'
    = f.label :description, class: 'col-form-label'
    = f.text_area :description, rows: 15, class: 'form-control'
    = f.label :order, class: 'col-form-label'
    = f.text_field :order, class: 'form-control'

    %br/
    = f.button 'Submit', class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form', product: @product

= link_to 'Show', @product

app/views/products/index.html.haml
.h3.text-center
  Products
  - if current_user.has_role? :admin
    = link_to new_product_path do
      %i.fas.fa-plus

.card-columns
  - allow_edit = current_user.has_role? :admin
  - Product.enabled.order(order: :desc).each do |product|
    .card{ id: "product-#{product.id}" }
      = cl_image_tag product.photo.thumb, secure: true, class: 'card-img-top img-fluid'
      .card-body
        .card-title
          .float-left
            = link_to product_path(product), class: 'card-link' do
              = product.name
          .float-right
            = link_to add_product_cart_index_path(id: product.id), method: :post, remote: true do
              %i.fas.fa-cart-plus
            - if @cart.key? product.id.to_s
              = link_to remove_product_cart_index_path(id: product.id), method: :post, remote: true do
                %i.fas.fa-cart-arrow-down
            - if allow_edit
              = link_to edit_product_path(product) do
                %i.far.fa-edit
          .clearfix
        .card-text= product.description

app/views/products/new.html.haml
%h1 Registering a new product

= render 'form', product: @product

app/views/products/show.html.haml
.jumbotron.jumbotron-fluid
  .h3.text-center
    = @product.name
    - if current_user.has_role? :admin
      = link_to edit_product_path(@product) do
        %i.far.fa-edit

  = cl_image_tag @product.photo.standard, secure: true, class: 'card-img-top img-fluid'
  .lead
    = @product.description
  %hr.my-4
  %p.text-right Unit price: #{@product.price}円
  .lead.text-center
    = link_to add_product_cart_index_path(id: @product), method: :post, remote: true do
      Add to cart
      %i.fas.fa-cart-plus
  %hr.my-4
  .h3.text-center Reviews
  - @product.posts.with_username.each do |post|
    = render partial: 'posts/post',
             locals: { post: post,
                       liked_posts_ids: current_user.liked_posts.pluck(:id),
                       preview_mode: true }