config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 sign_up: 'register' }

  resources :admin, only: %i[index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  resources :likes, only: %i[create]
  resources :posts, only: %i[index]

  resources :products, except: %i[destroy] do
    resources :posts, except: %i[index] do
      resources :comments, only: %i[create]
      get 'liked', on: :collection
    end
  end

  resources :cart, only: %i[index] do
    collection do
      get :content, format: :json
      post :add_product
      post :remove_product
      post :checkout
    end
  end

  resources :orders, only: %i[index]

  root to: 'products#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title Market
    = csrf_meta_tags
    = csp_meta_tag

    - packs = (['common'] + (content_for(:packs) || '').split(/,/)).uniq
    = javascript_packs_with_chunks_tag(*packs, 'data-turbolinks-track': 'reload', defer: true)
    = yield :extra_js
    - no_css_packs = (content_for(:no_css_packs) || '').split(/,/).uniq
    - packs = packs.filter { |pack| !no_css_packs.include? pack }
    = stylesheet_packs_with_chunks_tag(*packs, media: 'all', 'data-turbolinks-track': 'reload')
    = yield :extra_styles

  %body
    .container
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %span.navbar-brand.mb-0.h1 Market
        %button.navbar-toggler{ type: 'button',
                               data: { toggle: 'collapse',
                                       target: '#navbarNav' },
                               aria: { controls: 'navbarNav',
                                       expanded: 'false',
                                       label: 'Toggle navigation' } }
          %span.navbar-toggler-icon
        .navbar-collapse.collapse#navbarNav
          .navbar-nav
            = link_to root_path, class: 'nav-item nav-link' do
              %i.fas.fa-tachometer-alt
              Home
            - if Post.exists?
              = link_to posts_path, class: 'nav-item nav-link' do
                %i.fas.fa-comments
                Voices
            - if user_signed_in?
              = link_to cart_index_path, class: 'nav-item nav-link' do
                %i.fas.fa-shopping-cart
                Cart
              - if current_user.orders.exists?
                = link_to orders_path, class: 'nav-item nav-link' do
                  %i.fas.fa-history
                  Orders
              - if current_user.has_role? :admin
                = link_to admin_index_path, class: 'nav-item nav-link' do
                  %i.fas.fa-user-shield
                  Admin
              = link_to edit_user_registration_path, class: 'nav-item nav-link' do
                %i.fas.fa-user-cog
                User settings
              = link_to destroy_user_session_path, class: 'nav-item nav-link', method: :delete do
                %i.fas.fa-sign-out-alt
                Logout

      %br/

      - flash.each do |flash_type, flash_content|
        .alert{ class: "alert-#{flash_type} alert-dismissible fade show",
                role: 'alert' }
          = flash_content
          %button.close{ type: 'button',
                         'data-dismiss': 'alert',
                         'aria-label': 'Close' }
            %span{ 'aria-hidden': 'true' }
              &times;

      = yield

      - if current_user != true_user
        .text-center.text-danger
          o-o-o You are currently signed in as [#{current_user.username}] -
          = link_to 'Cancel impersonation', stop_impersonating_admin_index_path, method: :post
          o-o-o